# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: loops_cli

before:
  hooks:
    - go mod tidy

builds:
  - binary: loops
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/loops-so/cli/cmd.version={{.Version}}
      - -X github.com/loops-so/cli/cmd.commit={{.ShortCommit}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

homebrew_casks:
  - name: loops
    repository:
      owner: loops-so
      name: homebrew-loops
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://loops.so
    description: Official CLI for Loops
    binaries: [loops]

changelog:
  use: github-native
