# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: run the loops cli in dev
    dotenv:
      - .env
      - .env.{{.ENV}}
    cmds:
      - go run ./... {{.CLI_ARGS}}
    silent: true

  deps:
    desc: install/update deps
    cmds:
      - go mod tidy

  build:
    desc: build the cli
    deps:
      - deps
    cmds:
      - go build -o dist/loops

  test:
    desc: run tests
    cmds:
      - go test ./... -cover

  vuln:
    desc: run govulncheck
    cmds:
      - go tool govulncheck {{.CLI_ARGS}} ./...

  release:
    desc: release a new cli version
    deps:
      - release:check
    requires:
      vars:
        - tag
    cmds:
      - git pull --rebase
      - git tag {{.tag}}
      - git push origin {{.tag}}
    preconditions:
      - sh: '[ -z "$(git ls-remote --tags origin refs/tags/{{.tag}})" ]'
        msg: "tag {{.tag}} already exists on remote"
      - sh: '[ "$(git branch --show-current)" = "main" ]'
        msg: make sure you're on main

  release:local:
    desc: build with goreleaser
    cmds:
      - goreleaser release --snapshot --clean

  release:check:
    cmds:
      - goreleaser check
