# https://taskfile.dev

version: "3"

tasks:
  default:
    dotenv:
      - .env
      - .env.{{.ENV}}
    cmds:
      - go run ./... {{.CLI_ARGS}}

  deps:
    cmds:
      - go mod tidy

  build:
    deps:
      - deps
    cmds:
      - go build -o dist/loops

  test:
    cmds:
      - go test ./...

  vuln:
    cmds:
      - go tool govulncheck {{.CLI_ARGS}} ./...
